from flask import Flask, render_template, request, jsonify
import openai

app = Flask(__name__)

# Set your OpenAI API key here
openai.api_key = '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'


# Home route
def create_packaging_kit(profile):
    try:
        # Create prompt based on user profile
        prompt = f"Create a packaging kit based on the following user profile: {profile}"

        # OpenAI API call (using GPT-3 or GPT-4)
        response = openai.chat.completions.create(
            model="gpt-4",
            messages=[
                {
                    "role": "system",
                    "content": "You are a packaging expert. Help users create the best packaging kit based on their profiles."
                },
                {
                    "role": "user",
                    "content": prompt,
                }
            ],

            temperature=0.8
        )

        # Extract the text generated by the model
        return response.choices[0].message.content.strip()
    except Exception as e:
        return f"An error occurred: {str(e)}"


@app.route('/')
def index():
    return render_template('index.html')


@app.route('/generate_packaging_kit', methods=['POST'])
def generate_packaging_kit():
    profile = {
        "first_name": request.form.get('first_name'),
        "last_name": request.form.get('last_name'),
        "email": request.form.get('email'),
        "phone_number": request.form.get('phone_number'),
        "gender": request.form.get('gender'),
        "dob": request.form.get('dob'),
        "address": request.form.get('address'),
        "allergies": request.form.getlist('allergies')
    }
    kit = create_packaging_kit(profile)
    return render_template('kit.html', kit=kit)


if __name__ == '__main__':
    app.run(debug=True)
