# Generated by Django 5.0.6 on 2024-10-24 19:11

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kid_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gov_fname', models.CharField(blank=True, default='Unknown', max_length=255, null=True)),
                ('gov_lname', models.CharField(blank=True, default='Unknown', max_length=255, null=True)),
                ('guardian_email_address', models.EmailField(default='Unknown', max_length=254)),
                ('guardian_phone_number', models.CharField(max_length=12)),
                ('date_of_birth', models.DateField()),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', django_countries.fields.CountryField(default='Canada', max_length=2)),
                ('allergy', models.CharField(default='none', max_length=255)),
                ('dietary_restrictions', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
