# Generated by Django 5.0.6 on 2024-10-24 22:40

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kid_reg',
            name='dietary_restrictions',
        ),
        migrations.AddField(
            model_name='kid_reg',
            name='child_identification_document',
            field=models.ImageField(null=True, upload_to='mediafile/'),
        ),
        migrations.AddField(
            model_name='kid_reg',
            name='child_identification_type',
            field=models.CharField(default='Passport', max_length=255),
        ),
        migrations.AddField(
            model_name='kid_reg',
            name='current_medication',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='kid_reg',
            name='doctor_phone_number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='kid_reg',
            name='emergency_contact_fullname',
            field=models.CharField(blank=True, default='Unknown', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kid_reg',
            name='emergency_contact_phone_number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='kid_reg',
            name='family_medical_history',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='kid_reg',
            name='guardian_identification_document',
            field=models.ImageField(null=True, upload_to='mediafile/'),
        ),
        migrations.AddField(
            model_name='kid_reg',
            name='guardian_identification_type',
            field=models.CharField(default='Passport', max_length=255),
        ),
        migrations.AddField(
            model_name='kid_reg',
            name='insurance_policy_number',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='kid_reg',
            name='insurance_provider',
            field=models.CharField(blank=True, default='Unknown', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kid_reg',
            name='medical_conditions',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='kid_reg',
            name='primary_care_doctor',
            field=models.CharField(blank=True, default='Unknown', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kid_reg',
            name='sex',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kid_reg',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kid_reg',
            name='country',
            field=django_countries.fields.CountryField(default='CA', max_length=2),
        ),
        migrations.AlterField(
            model_name='kid_reg',
            name='gov_fname',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='kid_reg',
            name='gov_lname',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='kid_reg',
            name='guardian_phone_number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='kid_reg',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kid_reg',
            name='street_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kid_reg',
            name='zip_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
