# Generated by Django 5.0.6 on 2024-10-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journi', '0003_kid_reg_group_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kid_reg',
            name='guardian_email_address',
        ),
        migrations.RemoveField(
            model_name='kid_reg',
            name='guardian_phone_number',
        ),
        migrations.AddField(
            model_name='kid_reg',
            name='emergency_email_address',
            field=models.EmailField(blank=True, default='Unknown', max_length=254),
        ),
        migrations.AlterField(
            model_name='kid_reg',
            name='gov_fname',
            field=models.CharField(blank=True, default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='kid_reg',
            name='gov_lname',
            field=models.CharField(blank=True, default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='kid_reg',
            name='sex',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
