# Generated by Django 5.0.6 on 2024-10-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journi', '0004_remove_kid_reg_guardian_email_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid_reg',
            name='doctor_hospital_address',
            field=models.CharField(blank=True, default='Unknown', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kid_reg',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kid_reg',
            name='current_medication',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='kid_reg',
            name='doctor_phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='kid_reg',
            name='emergency_contact_phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='kid_reg',
            name='group_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='kid_reg',
            name='insurance_policy_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='kid_reg',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kid_reg',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kid_reg',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
