# Generated by Django 5.0.6 on 2024-10-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journi', '0006_remove_kid_reg_child_identification_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid_reg',
            name='emergency_email_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
