# Generated by Django 5.0.6 on 2024-10-26 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journi', '0007_alter_kid_reg_emergency_email_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kid_reg',
            old_name='emergency_email_address',
            new_name='emergency_contact_email_address',
        ),
    ]
